open-formulieren/formio-builder

- src/components/ComponentPreview.tsx
- src/components/builder/prefill/prefill.stories.tsx
- src/components/formio/component.tsx
- src/components/formio/textfield.tsx
- src/registry/index.tsx
- src/registry/textfield/edit-validation.ts
- src/registry/validation.ts
- src/utils/errors.tsx
Extracted the refactor code from #17 so that don't have to duplicate work when adding the typescript types from https://github.com/open-formulieren/types in a follow up PR.
> Refactors extracted from email feature PR

- src/components/ComponentEditForm.stories.tsx
- src/components/ComponentPreview.tsx
- src/components/JSONEdit.tsx
Closes #42
I don't know how to approach the autogenerated component key from the label :( It's tracked on the form field itself whether it was set manually or automatically, so the formik `setValues` doesn't know or has no way communicate that the key from the JSON should be taken.
> Add minimal edit-json mode to builder

- .storybook/decorators.tsx
- i18n/messages/en.json
- i18n/messages/nl.json
- package-lock.json
- package.json
- src/components/ComponentConfiguration.stories.tsx
- src/components/ComponentConfiguration.tsx
- src/components/ComponentEditForm.tsx
- src/components/ComponentPreview.stories.tsx
- src/components/builder/validate/validator-select.stories.tsx
- src/components/formio/component.tsx
- src/components/formio/description.tsx
- src/components/formio/multiple.tsx
- src/components/formio/select.tsx
- src/components/formio/textfield.tsx
- src/context.ts
- src/registry/file/edit-validation.ts
- src/registry/file/edit.tsx
- src/registry/file/file-tab.stories.ts
- src/registry/file/file-tab.tsx
- src/registry/file/file-validation.stories.ts
- src/registry/file/index.ts
- src/registry/file/preview.tsx
- src/registry/file/registration-tab.stories.ts
- src/registry/file/registration-tab.tsx
- src/registry/index.tsx
- src/registry/types.ts
Partly fixes open-formulieren/open-forms#2958
Implement the file component in the new form builder, which scopes the translations to the component itself and should resolve these translation issues.
> Implement file component

- src/components/ComponentConfiguration.stories.tsx
- src/components/ComponentPreview.stories.tsx
- src/components/formio/index.ts
- src/components/formio/radio.stories.ts
- src/components/formio/radio.tsx
- src/registry/index.tsx
- src/registry/radio/edit-validation.ts
- src/registry/radio/edit.tsx
- src/registry/radio/helpers.ts
- src/registry/radio/index.ts
- src/registry/radio/preview.tsx
- src/registry/radio/radio-validation.stories.ts
Closes #56
Very similar to the selectboxes component, so the code is mostly copy pasted :grimacing:
> Implement radio component edit form

- src/components/ComponentConfiguration.stories.tsx
- src/components/ComponentPreview.stories.tsx
- src/components/ComponentPreview.tsx
- src/components/JSONPreview.tsx
- src/components/builder/values/values-config.stories.tsx
- src/components/builder/values/values-config.tsx
- src/components/formio/select.tsx
- src/registry/index.tsx
- src/registry/select/edit-validation.ts
- src/registry/select/edit.tsx
- src/registry/select/helpers.ts
- src/registry/select/index.ts
- src/registry/select/preview.tsx
- src/registry/select/select-validation.stories.ts
> Implement the select component edit form

- package-lock.json
- package.json
Doing this as a separate PR so that we can (hopefully) get it merged so everyone can continue working on features that depend on it in parallel.
> :arrow_up: Upgrade to types v0.18.1

- src/components/ComponentConfiguration.stories.tsx
- src/components/ComponentConfiguration.tsx
- src/context.ts
- src/tests/test-utils.tsx
There no longer is a store outside of the control of a component, instead, all translations are now stored on the component itself.
> Delete dead translations code

- src/components/builder/multiple.tsx
- src/registry/file/edit.stories.ts
- src/registry/file/edit.tsx
Discovered while investigating open-formulieren/open-forms#3858
`defaultValue: [null]` crashes the preview (rightfully so).
The backend/Formio adds the `defaultValue: null`, so when toggling multiple, this turns it into `[null]`. Setting it to `defaultValue: []` (always) results in `[[]]` which is also wrong.
The `Multiple` component should not be aware of special behaviour for particular component types, so instead we allow the component edit form to control whether it can touch the `defaultValue` or not.
> Fix multiple option breaking form preview

- src/components/builder/simple-conditional.tsx
- src/registry/content/edit.tsx
Closes open-formulieren/open-forms#3920
I added the isClearable prop. This component doesn't have the prop required so, I think that this is enough. I thought maybe I need to look if it is required because then the `isClearable` should be to false.
> :bug: [#3920] add isClearable to simpleConditional

- src/components/ComponentConfiguration.stories.tsx
- src/registry/selectboxes/edit.tsx
Only 'required' could have a custom error message, while we recently added 'minSelectedCount' and 'maxSelectedCount' too.
Stumbled upon it via open-formulieren/open-forms#72
> :bug: Add missing error message codes for selectboxes

- src/registry/date/edit.tsx
- src/registry/datetime/edit.tsx
489887af9b9fc48044efc0fe4b04e097ace53046 removed the marker for validation errors because of dynamic min/max date validation behaviour.
I'll set up visual regression testing with chromatic for this because we keep ping-ponging back and forth.
> :bug: Fix regression in validation error tab markings

- i18n/messages/en.json
- i18n/messages/nl.json
- package-lock.json
- package.json
- src/registry/addressNL/edit.tsx
- src/registry/addressNL/index.ts
- src/registry/addressNL/preview.tsx
Partly fixes open-formulieren/open-forms#3993
> [OF#3993] Add deriveAddress boolean to addressNL component

- package-lock.json
- package.json
- src/registry/textarea/edit.tsx
- src/registry/textfield/edit.tsx
Partly closes open-formulieren/open-forms#4362
Depends on https://github.com/open-formulieren/types/pull/49
It is unused and too complex with 'multiple: true' cases, causing crashes in the admin interface.
> Remove support for defaultValue translations

- i18n/messages/en.json
- i18n/messages/nl.json
- src/registry/textfield/edit.tsx
Update the builder to steer people to the new component instead of using the legacy configuration.
> Deprecate textfield location derivation

- i18n/messages/en.json
- i18n/messages/nl.json
- package-lock.json
- package.json
- src/components/ComponentPreview.stories.tsx
- src/components/ComponentPreview.tsx
- src/components/formio/textfield.tsx
- src/registry/email/edit.tsx
- src/registry/email/preview.tsx
- src/registry/email/previews.scss
Partially closes open-formulieren/open-forms#4542
* Added preview for email-with-verification (dummy button)
* Added verification option to the validation tab
> Add support for email verification

- i18n/messages/en.json
- i18n/messages/nl.json
- src/components/ComponentConfiguration.stories.tsx
- src/components/builder/validate/i18n.tsx
- src/components/formio/datamap.tsx
- src/registry/addressNL/edit.stories.ts
- src/registry/addressNL/edit.tsx
partially closes https://github.com/open-formulieren/open-forms/issues/4420
~~Requires https://github.com/open-formulieren/types/pull/51 to be merged and released first~~
> :sparkles: [#4420] Validation for fields within AddressNL component

- src/components/builder/i18n.stories.tsx
- src/components/builder/i18n.tsx
- src/components/builder/index.ts
- src/components/builder/table.scss
- src/components/builder/values/i18n.tsx
Closes open-formulieren/open-forms#4636
All data a user can input shouldn't be allowed to break the table
> :bug: [open-formulieren/open-forms#4636] Preventing large values from breaking the table

- package-lock.json
- package.json
- src/components/ComponentConfiguration.stories.tsx
- src/registry/select/edit.tsx
Fixes open-formulieren/open-forms#4772 partially
Requires https://github.com/open-formulieren/types/pull/58 to be merged/released/bumped
because Select components did not have a dataType set, formio tries to cast it to other types if possible, which causes issues when submitting the data to the backend. For that reason we set the value to string to avoid this unwanted normalization
> :bug: [open-formulieren/open-forms#4772] Set select dataType to string

- src/context.ts
- src/registry/file/registration-tab.tsx
- src/tests/sharedUtils.tsx
Part of open-formulieren/open-forms#4606 - needs to be part of open-formulieren/open-forms#4817
The backend makes the API serializers more uniformly English in 3.0
> Handle API serializer renames in the backend

- i18n/messages/en.json
- i18n/messages/nl.json
- src/registry/file/registration-tab.tsx
Closes open-formulieren/open-forms#4319 partly
> [OF#4319] Update tooltip in the file upload component's title field

- src/components/ComponentConfiguration.stories.tsx
- src/components/ComponentPreview.stories.tsx
- src/registry/addressNL/index.ts
- src/registry/addressNL/preview.tsx
Closes open-formulieren/open-forms#5006 partly
Requires:
> [OF#5006] Update addressNL component with `autoPopulated` field

- src/components/ComponentConfiguration.stories.tsx
- src/registry/file/edit.tsx
closes open-formulieren/open-forms#5025 partially (will also have to be released + updated in the backend)
> :sparkles: [open-formulieren/open-forms#5025] Use generally configured filetypes by default

- src/components/formio/component-label.scss
- src/components/formio/component-label.tsx
Closes open-formulieren/open-forms#5105
~The asterisks on required fields have a z-index of 10. This is part of base formio styling, so no idea why this is. Instead of lowering this, I've opted to raise the select component menu.~
Edit: So I've changed this to indeed remove the z-index from the required field asterisks. Raising the select menu is also an option, but that scares me a bit more
> Removing zIndex from required field asterisks

- i18n/messages/en.json
- i18n/messages/nl.json
- src/components/ComponentPreview.tsx
- src/components/error/ErrorBoundary.stories.tsx
- src/components/error/ErrorBoundary.tsx
- src/components/error/GenericError.tsx
- src/registry/map/map-configuration.tsx
Partly closes open-formulieren/open-forms#5191
Adding a ErrorBoundary component, with generic error handling, to make sure that errors thrown in the component preview don't crash the component modal.
> Catching component preview errors
