open-formulieren/formio-builder

src/components/ComponentConfiguration.stories.tsx
src/components/ComponentEditForm.tsx
src/components/ComponentPreview.stories.tsx
src/components/ComponentPreview.tsx
src/components/formio/description.tsx
src/components/formio/index.ts
src/components/formio/textfield.tsx
src/registry/index.tsx
src/registry/textfield/edit.tsx
src/registry/textfield/index.ts
src/registry/textfield/preview.tsx
src/types/index.d.ts
src/types/schemas.d.ts

Add component preview for textfield

---

package-lock.json
package.json
src/components/ComponentEditForm.tsx
src/components/formio/checkbox.stories.tsx
src/components/formio/checkbox.tsx
src/components/formio/component.stories.tsx
src/components/formio/component.tsx
src/components/formio/number.stories.tsx
src/components/formio/number.tsx
src/components/formio/select.stories.tsx
src/components/formio/select.tsx
src/components/formio/tabs.stories.tsx
src/components/formio/tabs.tsx
src/components/formio/textfield.stories.tsx
src/components/formio/textfield.tsx
src/registry/index.tsx
src/registry/textfield/edit-validation.ts
src/registry/textfield/edit.tsx
src/registry/textfield/index.ts
src/utils/errors.stories.ts
src/utils/errors.ts
tsconfig.json

Builder validation for textfield

---

.github/workflows/ci.yml
.gitignore
README.md
bin/find_untranslated_messages.py
bin/i18n-formatter.js
bin/makemessages.sh
i18n/messages/en.json
i18n/messages/nl.json
package-lock.json
package.json

Closes #5
Using the convention approach to put files in the correct location.

Distribute translations / i18n flow

---

.storybook/preview.js
README.md
i18n/messages/en.json
i18n/messages/nl.json
package-lock.json
package.json
src/components/ComponentConfiguration.stories.tsx
src/components/ComponentPreview.stories.tsx
src/components/ComponentPreview.tsx
src/components/formio/component-label.stories.tsx
src/components/formio/component-label.tsx
src/components/formio/component.tsx
src/components/formio/multiple.tsx
src/components/formio/textfield.stories.tsx
src/components/formio/textfield.tsx
src/context.ts
src/registry/index.tsx
src/registry/textfield/edit.tsx
src/registry/textfield/index.ts
src/registry/textfield/preview.tsx
src/utils/charcount.tsx

Closes #7
There is extensive context/documentation in the commit messages.

Implement the 'multiple' flag for textfield component

---

src/components/ComponentConfiguration.stories.tsx
src/components/builder/index.ts
src/components/builder/tooltip.stories.tsx
src/components/builder/tooltip.tsx
src/registry/textfield/edit.tsx
src/registry/textfield/preview.tsx

Related to open-formulieren/open-forms#1892

Add setting tooltip on component

---

src/components/builder/prefill/identifierRole.tsx
src/components/builder/prefill/index.tsx
src/components/builder/prefill/prefill.stories.tsx
src/registry/textfield/edit.tsx
src/types/schemas.d.ts

Fixes open-formulieren/open-forms#3215

[OF#3215] Add configuration for prefill identifier role

---

src/components/ComponentEditForm.tsx
src/components/ComponentPreview.tsx
src/components/builder/multiple.tsx
src/components/formio/checkbox.tsx
src/registry/date/edit.tsx
src/registry/email/edit.tsx
src/registry/index.tsx
src/registry/textfield/edit.tsx
src/registry/textfield/textfield-component.stories.ts

Closes #21 
This now has the same interaction as form.io's builder/preview itself.

Default value + multiple toggle handling in preview

---

.github/workflows/ci.yml
src/components/ComponentConfiguration.stories.tsx
src/registry/textfield/textfield-component.stories.ts

Firefox is flaky locally, let's see if that's also the case in CI and fix it.

:construction_worker: Run storybook tests in the three major browsers

---

package-lock.json
package.json
src/components/formio/checkbox.stories.tsx
src/components/formio/checkbox.tsx
src/registry/checkbox/edit-validation.ts
src/registry/checkbox/edit.tsx
src/registry/checkbox/index.ts
src/registry/checkbox/preview.tsx

I can't test the storybook locally as running build/watch crashes my computer

✨ Add `checkbox` component

---

README.md
package-lock.json
package.json
src/registry/iban/preview.tsx

This should allow us to implement more builder forms :tada:

Update to @open-formulieren/types 0.15.0

---

src/components/ComponentConfiguration.stories.tsx
src/components/ComponentPreview.stories.tsx
src/registry/bsn/edit-validation.ts
src/registry/bsn/edit.tsx
src/registry/bsn/index.ts
src/registry/bsn/preview.tsx
src/registry/index.tsx

Implement edit form form BSN component

---

src/components/ComponentConfiguration.stories.tsx
src/registry/index.tsx

Stories for components that are implemented but not documented in storybook yet.
Built on top of #63, so that should be merged first and then I'll rebase

Add missing stories

---

README.md
src/components/ComponentConfiguration.stories.tsx
src/components/ComponentPreview.stories.tsx
src/registry/index.tsx
src/registry/npFamilyMembers/edit-validation.ts
src/registry/npFamilyMembers/edit.tsx
src/registry/npFamilyMembers/index.ts
src/registry/npFamilyMembers/preview.tsx

Implement Family Members component in builder form

---

src/components/ComponentConfiguration.stories.tsx
src/components/ComponentPreview.stories.tsx
src/registry/columns/columns-validation.stories.ts
src/registry/columns/edit-validation.ts
src/registry/columns/edit.tsx
src/registry/columns/index.ts
src/registry/columns/preview.tsx
src/registry/index.tsx

Closes #72
The preview implementation led me to revisit our implementation the SDK too: https://github.com/open-formulieren/open-forms-sdk/pull/604

Implement columns component edit form

---

README.md
src/components/ComponentConfiguration.stories.tsx
src/components/ComponentPreview.stories.tsx
src/registry/fieldset/edit-validation.ts
src/registry/fieldset/edit.tsx
src/registry/fieldset/index.ts
src/registry/fieldset/preview.tsx
src/registry/index.tsx

Closes #74
Built on top of #73

Implement fieldset component

---

.storybook/decorators.tsx
README.md
package-lock.json
package.json
src/components/ComponentConfiguration.stories.tsx
src/components/ComponentConfiguration.tsx
src/components/ComponentPreview.stories.tsx
src/components/formio/select.tsx
src/context.ts
src/registry/cosignV1/edit-validation.ts
src/registry/cosignV1/edit.tsx
src/registry/cosignV1/index.ts
src/registry/cosignV1/preview.tsx
src/registry/cosignV2/edit-validation.ts
src/registry/cosignV2/edit.tsx
src/registry/cosignV2/index.ts
src/registry/cosignV2/preview.tsx
src/registry/index.tsx

Implement cosign components

---

package-lock.json
package.json
src/components/builder/prefill/prefill.stories.tsx
src/components/builder/registration/registration-attribute.spec.tsx
src/components/builder/validate/validator-select.stories.tsx
src/components/builder/values/values-config.stories.tsx
src/registry/columns/columns.spec.tsx
src/registry/file/file-validation.stories.ts
src/registry/selectboxes/selectboxes-validation.stories.ts
src/registry/textfield/textfield-component.stories.ts

Upgrade to React 18

---

src/registry/validation.spec.ts
src/tests/test-utils.tsx

Add a test for open-formulieren/open-forms#3668 behaviour.

(Deliberately) allow any string for values

---

.storybook/decorators.tsx
README.md
package-lock.json
package.json
src/components/ComponentConfiguration.stories.tsx
src/components/ComponentConfiguration.tsx
src/components/ComponentEditForm.tsx
src/components/ComponentPreview.tsx
src/components/formio/component.tsx
src/components/formio/select.tsx
src/context.ts
src/registry/content/content.stories.ts
src/registry/content/edit-validation.ts
src/registry/content/edit.tsx
src/registry/content/index.ts
src/registry/content/rich-text.tsx
src/registry/fallback/index.tsx
src/registry/index.tsx
src/registry/types.ts
src/tests/sharedUtils.tsx
src/tests/test-utils.tsx

Implement content component

---

src/components/ComponentConfiguration.stories.tsx
src/registry/index.tsx
src/registry/password/edit-validation.ts
src/registry/password/edit.tsx
src/registry/password/index.ts
src/registry/password/preview.tsx

[#99] Implement `password` component

---

package-lock.json
package.json
src/registry/currency/edit-validation.spec.ts
src/registry/currency/edit-validation.ts
src/registry/currency/edit.tsx
src/registry/number/edit-validation.spec.ts
src/registry/number/edit-validation.ts
src/registry/number/edit.tsx
src/tests/EditorStub.ts
src/tests/test-utils.tsx

Nullable defaultValue for currency/number components

---

.storybook/preview.ts
package-lock.json
package.json
src/components/builder/tooltip.stories.tsx
src/components/formio/tooltip.stories.tsx
src/components/formio/tooltip.tsx

Closes #35
This has better handling for overflow, accessibility and is more customizable. Additionally, it allows rendering any ReactNode instead of being limited to strings only.
The clipping/overflow behaviour is still a bit wonkey - because the modal itself applies `overflow: hidden` and that would require us to set up manual overflow checking. Considering the UI of the form designer, I don't expect any issues here and the tooltips behave correctly in the main `ComponentConfiguration` stories.

:children_crossing: Use floating-ui for tooltip implementation

---

src/registry/date/date-component.stories.ts
src/registry/date/edit-validation.spec.ts
src/registry/date/edit-validation.ts
src/registry/date/validation/index.tsx
src/registry/datetime/datetime-component.stories.ts
src/registry/datetime/edit-validation.ts
src/registry/datetime/validation/index.tsx
src/utils/errors.tsx

Part of open-formulieren/open-forms#3733

Fix fixedValue date/datetime validation mode

---

src/components/ComponentPreview.tsx
src/components/JSONPreview.tsx

Part of https://github.com/open-formulieren/open-forms/issues/3774

[open-formulieren/open-forms#3774] Fix dark mode compatibility

---

package-lock.json
package.json
src/registry/date/edit.tsx
src/registry/datetime/edit.tsx

Fixes https://github.com/open-formulieren/open-forms/issues/3755

[OF#3755] Add custom options for flatpickr to the date/datetime components

---

src/registry/time/edit-validation.ts

Part of https://github.com/open-formulieren/open-forms/issues/3616

[open-formulieren/open-forms#3616] Fix zod schema for time component

---

package-lock.json
package.json
src/components/ComponentConfiguration.stories.tsx
src/components/formio/select.tsx

Partly fixes open-formulieren/open-forms#3774

Support dark mode for the react-select widgets

---

src/components/ComponentConfiguration.stories.tsx
src/registry/cosignV2/edit.tsx

Fixes open-formulieren/open-forms#3680

[OF#3680] Remove forgotten AuthPlugin component

---

i18n/messages/en.json
i18n/messages/nl.json
src/registry/selectboxes/edit-validation.ts
src/registry/selectboxes/edit.tsx
src/registry/selectboxes/selectboxes-validation.stories.ts

Fixes open-formulieren/open-forms#3727

[OF#3727] Add min/max count for selectboxes

---

CHANGELOG.md
package-lock.json
package.json

Fixes open-formulieren/open-forms#3727

Prepare release 0.16.0

---

package-lock.json
src/components/builder/prefill/attribute.tsx
src/components/builder/prefill/plugin.tsx
src/components/builder/prefill/prefill.spec.tsx
src/components/builder/prefill/prefill.stories.tsx
src/components/formio/select.stories.tsx
src/components/formio/select.tsx
src/registry/bsn/edit.tsx
src/registry/columns/columns.spec.tsx
src/registry/date/edit.tsx
src/registry/datetime/edit.tsx
src/registry/postcode/edit.tsx
src/registry/textfield/edit.tsx

Partly fixes open-formulieren/open-forms#3922

Fix default/empty values for component prefill configuration

---

src/registry/currency/edit-validation.ts
src/registry/number/edit-validation.ts

Fixes open-formulieren/open-forms#3943.
Did the same as the currency component (this this comment: https://github.com/open-formulieren/formio-builder/pull/50#discussion_r1386164089), but then figured out a better solution

[open-formulieren/open-forms#3943] Fix validation of number decimal places

---

src/components/builder/values/i18n.tsx
src/components/builder/values/option-row.tsx
src/components/builder/values/values-config.tsx
src/components/builder/values/values-table.tsx
src/components/formio/checkbox.stories.tsx
src/components/formio/checkbox.tsx
src/components/formio/component-label.tsx
src/components/formio/radio.stories.ts
src/components/formio/radio.tsx
src/components/formio/selectboxes.stories.ts
src/components/formio/selectboxes.tsx
src/registry/radio/edit.tsx
src/registry/selectboxes/edit.tsx

Closes open-formulieren/open-forms-sdk#483

:sparkles: [#483] add description for radio en checkbox option

---

CHANGELOG.md
i18n/messages/en.json
i18n/messages/nl.json
package-lock.json
package.json

* Added/updated translations
* Updated & cleaned up changelog

Release 0.18.0

---

src/registry/select/edit.tsx
src/registry/select/select.spec.tsx

Partly fixes open-formulieren/open-forms#4084

[open-formulieren/open-forms#4084] Fix default value of multiple `select` component

---

src/registry/date/edit.tsx
src/registry/datetime/edit.tsx

Fixes open-formulieren/open-forms#4155

[open-formulieren/open-forms#4155] Fix date and datetime validation tab errors

---

CHANGELOG.md
package-lock.json
package.json

Let's also include https://github.com/open-formulieren/formio-builder/pull/144

:bookmark: Bump to version `0.18.2`

---

src/components/ComponentConfiguration.stories.tsx
src/components/builder/simple-conditional.tsx
src/registry/checkbox/edit.tsx
src/registry/checkbox/index.ts
src/registry/currency/edit.tsx
src/registry/currency/index.ts
src/registry/number/edit.tsx
src/registry/number/index.ts
src/registry/types.ts

Fixes https://github.com/open-formulieren/open-forms/issues/2900, https://github.com/open-formulieren/open-forms/issues/3964 (partially)

[OF#3964,#2900] Special simple conditional for checkboxes

---

src/components/formio/radio.stories.ts
src/components/formio/radio.tsx
src/registry/radio/edit.tsx
src/registry/radio/preview.tsx

Fixes open-formulieren/open-forms#4064

[OF#4064] Ability to remove default value from radio

---

i18n/messages/en.json
i18n/messages/nl.json
package-lock.json
package.json
src/registry/addressNL/edit.tsx

Partly fixes https://github.com/open-formulieren/open-forms/issues/4423

[OF#4423] Add single/double column layout to the addressNL component

---

i18n/messages/en.json
i18n/messages/nl.json
src/registry/selectboxes/edit.tsx

partially fixes open-formulieren/open-forms#4505

:speech_balloon: [open-formulieren/open-forms#4505] Change selectboxes validation placeholders

---

src/context.ts
src/registry/file/registration-tab.stories.ts
src/registry/file/registration-tab.tsx
src/tests/sharedUtils.tsx
src/tests/test-utils.tsx

Partly fixes open-formulieren/open-forms#4267

[open-formulieren/open-forms#4267] Take new IOT API endpoint into account

---

i18n/messages/nl.json

From https://github.com/open-formulieren/open-forms/pull/4556#discussion_r1691673920

:speech_balloon: Update terms for identifier role

---

src/components/formio/select.tsx

So that the django admin can re-use it.

:recycle: export dark mode styles for react-select

---

.storybook/decorators.tsx
i18n/messages/en.json
i18n/messages/nl.json
package-lock.json
package.json
src/components/ComponentConfiguration.stories.tsx
src/components/ComponentConfiguration.tsx
src/components/ComponentPreview.stories.tsx
src/context.ts
src/registry/index.ts
src/registry/productPrice/edit-validation.ts
src/registry/productPrice/edit.tsx
src/registry/productPrice/index.ts
src/registry/productPrice/preview.tsx
src/tests/sharedUtils.tsx
src/tests/test-utils.tsx

Adds the product price component.
this component will be able to select a product which will be used to get its current prices when a user opens the form.
"getProducts" is added to the BuilderContext to be able to fetch the products for the product select.

add product price component

---

i18n/messages/nl.json

Partly closes open-formulieren/open-forms#4320
Non-crucial patch since it only affects the admin interface, but let's do it anyway to be consistent.

Update literals for co signing

---

package.json
src/components/ComponentConfiguration.stories.tsx
src/components/ComponentEditForm.spec.tsx
src/components/ComponentPreview.stories.tsx
src/components/builder/simple-conditional.stories.tsx
src/components/builder/validate/i18n.stories.tsx
src/components/formio/component-label.stories.tsx
src/components/formio/panel.stories.tsx
src/registry/addressNL/edit.stories.ts
src/registry/date/date-component.stories.ts
src/registry/select/select-validation.spec.tsx
src/registry/select/select.spec.tsx
src/tests/test-utils.tsx
tsconfig.json
tsconfig.prod.json

Our story and test files were not being type checked, and you can tell :grimacing:

Fix the type errors and lack of type checking

---

CHANGELOG.md
package-lock.json
package.json

Bump to version 0.38.0

---

i18n/messages/en.json
i18n/messages/nl.json
src/registry/radio/edit-validation.ts
src/registry/radio/radio-referentielijsten.stories.ts
src/registry/select/edit-validation.ts
src/registry/select/select-referentielijsten.stories.ts
src/registry/selectboxes/edit-validation.ts
src/registry/selectboxes/selectboxes-referentielijsten.stories.ts

Partly fixes open-formulieren/open-forms#5207

Add missing reference lists configuration validation

---

i18n/messages/en.json
i18n/messages/nl.json
package-lock.json
package.json
src/components/ComponentConfiguration.stories.tsx
src/components/ComponentPreview.stories.tsx
src/components/builder/is-sensitive-data.tsx
src/registry/index.ts
src/registry/partners/edit-validation.ts
src/registry/partners/edit.tsx
src/registry/partners/index.ts
src/registry/partners/preview.tsx

[#225] Add partners custom component
